// Central registry of all components in the library
// This file is auto-generated by scripts/generate-component-registry.js
// DO NOT EDIT MANUALLY - it will be overwritten!

export const COMPONENT_NAMES = ['Button', 'Icon'] as const;

export type ComponentName = (typeof COMPONENT_NAMES)[number];

// Auto-generated on: 2025-10-31T18:20:52.344Z
// Found components: Button, Icon
