// Central registry of all components in the library
// This file is auto-generated by scripts/generate-component-registry.js
// DO NOT EDIT MANUALLY - it will be overwritten!

export const COMPONENT_NAMES = ['Button', 'Icon', 'SectionHeader'] as const;

export type ComponentName = (typeof COMPONENT_NAMES)[number];

// Auto-generated on: 2025-11-02T04:49:24.005Z
// Found components: Button, Icon, SectionHeader
